### ISSUE TITLE
Zpětná vazba 

### ISSUE THREAD

**Issue by ifischerova** [MijaHinn/PROJEKT-Cukrarna#1]
Ahoj Míšo, 

super práce 👍 

Tipy:
- Kartičce `produkt` v Dnešní nabídka dát `overflow: hidden;`, tím se zakulatí i horní rohy fotografie.
- selektor `text-v-sekci a` bych asi dala spíš classu, která by rovnou vyjadřovala, že jde o tlačítko, usnadní to orientaci v kódu.
- Super, že sis našla vertical-align na zbavení se mezery pod obrázkem! :)
Ta mezera je tam proto, že obrázek se chová jako text, takže obrázek "sedí" na něčem, čemu se říká účaří a ta mezera je prostor pro takové ty smyčky a ocásky písmen jako "j", "g" apod. Dá se toho zbavit i tak, že vlastností `display: block;` změníš obrázek na blokový prvek. Pak by ani nemělo být potřeba obrázek balit do divu, ale bude stačit stylovat jen img.
- `<section>` klidně nemusí mít class "section", do css ji dáš přes selektor `section` místo `.section`

**Comment by MijaHinn** [comment]
Ahoj, děkuji za zpětnou vazbu. Nějak jsem úplně přehlédla, že jsem ty horní rohy neměla zakulacené, děkuji za tip :) ..Všechno opraveno :)

**Comment by ifischerova** [comment]
Ahoj, super 👍
